// Copyright (c) 2026 Randall Rosas (Slategray).
// All rights reserved.
//
// This source code is provided for educational and review purposes.
// Redistribution and use in binary form without express permission is prohibited.
// See LICENSE file in the project root for full terms.

#![no_std]

extern crate alloc;

pub mod adapter;
pub mod constants;
pub mod descriptors;
pub mod dispatch;
pub mod stream;
pub mod topology;
pub mod vtables;
pub mod wavert;

// First std/core.
use core::ptr::null_mut;

// Second, external crates.
use wdk_alloc::WdkAllocator;
// Second, external crates.
use wdk_sys::ntddk::*;
use wdk_sys::*;
#[cfg(not(test))]
extern crate wdk_panic;
// PUNKNOWN is often in wdk_sys directly or one of its modules.
// Bindgen usually generates it as *mut c_void or IUnknown.
// wdk_sys should have PUNKNOWN if we use it.
// Checking previous imports.

// Then current crate.
use crate::constants::*;
use crate::dispatch::*;

// Include generated bindings in a private module.
#[allow(clippy::all)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[allow(non_snake_case)]
#[allow(unused_imports)]
#[allow(dead_code)]
#[allow(clippy::unnecessary_cast)]
#[allow(clippy::useless_transmute)]
#[allow(clippy::too_many_arguments)]
#[allow(unnecessary_transmutes)]
pub mod audio {
    // Standard approach: use the bindings generated by build.rs in OUT_DIR.
    // If rust-analyzer fails to find them (e.g., due to eWDK environment issues),
    // it can use the shadow copy in src/audio_bindings.rs.
    #[cfg(not(rust_analyzer))]
    include!(concat!(env!("OUT_DIR"), "/audio_bindings.rs"));

    #[cfg(rust_analyzer)]
    include!("audio_bindings.rs");
}

pub use audio as audio_bindings;

#[global_allocator]
static GLOBAL: WdkAllocator = WdkAllocator;

// ============================================================================
// Global Driver State
// ============================================================================

#[no_mangle]
pub static mut CONTROL_DEVICE_OBJECT: *mut DEVICE_OBJECT = null_mut();

#[no_mangle]
pub static mut FUNCTIONAL_DEVICE_OBJECT: *mut DEVICE_OBJECT = null_mut();

static mut ETW_REG_HANDLE: u64 = 0;

/// Leyline Audio Driver ETW Provider GUID: {71549463-5E1E-4B7E-9F93-A65606E50D64}
const ETW_PROVIDER_GUID: GUID = GUID {
    Data1: 0x71549463,
    Data2: 0x5E1E,
    Data3: 0x4B7E,
    Data4: [0x9F, 0x93, 0xA6, 0x56, 0x06, 0xE5, 0x0D, 0x64],
};

// ============================================================================
// PortCls External Declarations
// ============================================================================

#[link(name = "portcls")]
extern "C" {
    pub fn PcInitializeAdapterDriver(
        DriverObject: PDRIVER_OBJECT,
        RegistryPath: PUNICODE_STRING,
        AddDevice: Option<unsafe extern "C" fn(PDRIVER_OBJECT, PDEVICE_OBJECT) -> NTSTATUS>,
    ) -> NTSTATUS;

    pub fn PcNewPort(OutPort: *mut *mut u8, ClassId: *const GUID) -> NTSTATUS;

    pub fn PcRegisterSubdevice(
        DeviceObject: PDEVICE_OBJECT,
        Name: *const u16,
        Unknown: *mut u8,
    ) -> NTSTATUS;

    pub fn PcAddAdapterDevice(
        DriverObject: PDRIVER_OBJECT,
        PhysicalDeviceObject: PDEVICE_OBJECT,
        StartDevice: Option<unsafe extern "C" fn(PDEVICE_OBJECT, PIRP, PVOID) -> NTSTATUS>,
        MaxObjects: u32,
        DeviceExtensionSize: u32,
    ) -> NTSTATUS;

    pub fn PcRegisterPhysicalConnection(
        DeviceObject: PDEVICE_OBJECT,
        FromUnknown: PVOID,
        FromPin: u32,
        ToUnknown: PVOID,
        ToPin: u32,
    ) -> NTSTATUS;
}

// ============================================================================
// Driver Entry Point
// ============================================================================

/// Driver entry point.
///
/// # Safety
/// Standard kernel DriverEntry. Parameters must be valid pointers provided by the OS.
#[unsafe(export_name = "DriverEntry")]
pub unsafe extern "system" fn driver_entry(
    driver_object: &mut DRIVER_OBJECT,
    registry_path: PCUNICODE_STRING,
) -> NTSTATUS {
    DbgPrint(c"Leyline: DriverEntry v1.0.150 (REBUILT)\n".as_ptr());

    // Register ETW Provider.
    let _ = EtwRegister(
        &ETW_PROVIDER_GUID,
        None,
        null_mut(),
        &raw mut ETW_REG_HANDLE,
    );

    driver_object.DriverUnload = Some(driver_unload);

    let status = PcInitializeAdapterDriver(
        driver_object as *mut DRIVER_OBJECT,
        registry_path as *mut _,
        Some(crate::adapter::AddDevice),
    );
    if status != STATUS_SUCCESS {
        return status;
    }

    DbgPrint(c"Leyline: PcInitializeAdapterDriver Success\n".as_ptr());

    // Safe CDO Dispatch Hooking.
    ORIGINAL_DISPATCH_CREATE = driver_object.MajorFunction[IRP_MJ_CREATE as usize];
    driver_object.MajorFunction[IRP_MJ_CREATE as usize] = Some(dispatch_create);

    ORIGINAL_DISPATCH_CLOSE = driver_object.MajorFunction[IRP_MJ_CLOSE as usize];
    driver_object.MajorFunction[IRP_MJ_CLOSE as usize] = Some(dispatch_close);

    ORIGINAL_DISPATCH_CONTROL = driver_object.MajorFunction[IRP_MJ_DEVICE_CONTROL as usize];
    driver_object.MajorFunction[IRP_MJ_DEVICE_CONTROL as usize] = Some(dispatch_device_control);

    status
}

/// Driver unload routine.
///
/// # Safety
/// Standard kernel DriverUnload callback.
pub unsafe extern "C" fn driver_unload(_driver_object: *mut DRIVER_OBJECT) {
    DbgPrint(c"Leyline: DriverUnload\n".as_ptr());

    if !CONTROL_DEVICE_OBJECT.is_null() {
        let mut link_name_str = [0u16; 25];
        let link_prefix = r"\DosDevices\LeylineAudio";
        for (i, c) in link_prefix.encode_utf16().enumerate() {
            link_name_str[i] = c;
        }
        let mut link_name = UNICODE_STRING {
            Length: (link_prefix.len() * 2) as u16,
            MaximumLength: (link_name_str.len() * 2) as u16,
            Buffer: link_name_str.as_mut_ptr(),
        };
        let _ = IoDeleteSymbolicLink(&mut link_name);
        IoDeleteDevice(CONTROL_DEVICE_OBJECT);
        CONTROL_DEVICE_OBJECT = null_mut();
        DbgPrint(c"Leyline: CDO and Symbolic Link Cleaned Up\n".as_ptr());
    }

    if ETW_REG_HANDLE != 0 {
        let _ = EtwUnregister(ETW_REG_HANDLE);
        ETW_REG_HANDLE = 0;
    }
}

// ============================================================================
// Stream Callbacks (Bridge to stream.rs)
// ============================================================================

/// QueryInterface for IMiniportWaveRTStream.
///
/// # Safety
/// Standard COM-like QueryInterface. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_query_interface(
    this: *mut u8,
    iid: *const GUID,
    out: *mut *mut u8,
) -> NTSTATUS {
    let com_obj = this as *mut crate::adapter::MiniportWaveRTStreamCom;
    if is_equal_guid(iid, &IID_IMiniportWaveRTStream) || is_equal_guid(iid, &IID_IUnknown) {
        (*com_obj).ref_count += 1;
        *out = this;
        return STATUS_SUCCESS;
    }

    *out = null_mut();
    STATUS_NOINTERFACE
}

/// AddRef for IMiniportWaveRTStream.
///
/// # Safety
/// Standard COM-like AddRef. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_add_ref(this: *mut u8) -> u32 {
    let com_obj = this as *mut crate::adapter::MiniportWaveRTStreamCom;
    (*com_obj).ref_count += 1;
    (*com_obj).ref_count
}

/// Release for IMiniportWaveRTStream.
///
/// # Safety
/// Standard COM-like Release. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_release(this: *mut u8) -> u32 {
    let com_obj = this as *mut crate::adapter::MiniportWaveRTStreamCom;
    (*com_obj).ref_count -= 1;
    let count = (*com_obj).ref_count;
    if count == 0 {
        drop(alloc::boxed::Box::from_raw(com_obj));
    }
    count
}

/// SetFormat callback.
///
/// # Safety
/// Standard PortCls callback. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_set_format(_this: *mut u8, _format: *mut u8) -> NTSTATUS {
    STATUS_SUCCESS
}

/// SetState callback.
///
/// # Safety
/// Standard PortCls callback. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_set_state(this: *mut u8, state: i32) -> NTSTATUS {
    let com_obj = this as *mut crate::adapter::MiniportWaveRTStreamCom;
    (*(*com_obj).stream).set_state(state)
}

/// GetPosition callback.
///
/// # Safety
/// Standard PortCls callback. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_get_position(this: *mut u8, position: *mut u64) -> NTSTATUS {
    let com_obj = this as *mut crate::adapter::MiniportWaveRTStreamCom;
    (*(*com_obj).stream).get_position(position)
}

/// AllocateAudioBuffer callback.
///
/// # Safety
/// Standard PortCls callback. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_allocate_audio_buffer(
    this: *mut u8,
    req_size: usize,
    mdl: *mut *mut u8,
    act_size: *mut usize,
    off: *mut u32,
    cache: *mut i32,
) -> NTSTATUS {
    let com_obj = this as *mut crate::adapter::MiniportWaveRTStreamCom;
    let status = (*(*com_obj).stream).allocate_audio_buffer(req_size, mdl as *mut PMDL);
    if status != STATUS_SUCCESS {
        return status;
    }

    if !act_size.is_null() {
        *act_size = req_size;
    }
    if !off.is_null() {
        *off = 0;
    }
    if !cache.is_null() {
        *cache = 1;
    }

    status
}

/// FreeAudioBuffer callback.
///
/// # Safety
/// Standard PortCls callback.
pub unsafe extern "system" fn stream_free_audio_buffer(
    _this: *mut u8,
    _mdl: *mut u8,
    _size: usize,
) {
}

/// GetHWLatency callback.
///
/// # Safety
/// Standard PortCls callback. Parameters must be valid pointers.
pub unsafe extern "system" fn stream_get_hw_latency(this: *mut u8, latency: *mut u32) {
    let com_obj = this as *mut crate::adapter::MiniportWaveRTStreamCom;
    (*(*com_obj).stream).get_hw_latency(latency);
}

/// GetPositionRegister callback.
///
/// # Safety
/// Standard PortCls callback.
pub unsafe extern "system" fn stream_get_position_register(
    _this: *mut u8,
    _reg: *mut u8,
) -> NTSTATUS {
    0xC00000BBu32 as i32
}

/// GetClockRegister callback.
///
/// # Safety
/// Standard PortCls callback.
pub unsafe extern "system" fn stream_get_clock_register(_this: *mut u8, _reg: *mut u8) -> NTSTATUS {
    0xC00000BBu32 as i32
}

/// Compares two GUIDs for equality.
///
/// # Safety
/// Parameter 'a' must be a valid pointer to a GUID.
pub unsafe fn is_equal_guid(a: *const GUID, b: &GUID) -> bool {
    (*a).Data1 == b.Data1 && (*a).Data2 == b.Data2 && (*a).Data3 == b.Data3 && (*a).Data4 == b.Data4
}
